### ISSUE TITLE
not working with 0.8.0

### ISSUE THREAD

**Issue by liquidzym** [arturoc/ofxHttpUtils#8]
ofxHttpUtils.obj : error LNK2019:unresolved external symbol "public: void __thiscall Poco::Net::HTTPBasicCredentials::authenticate(class Poco::Net::HTTPRequest &)" (?authenticate@HTTPBasicCredentials@Net@Poco@@QAEXAAVHTTPRequest@23@@Z)，该符号在函数 "protected: struct ofxHttpResponse __thiscall ofxHttpUtils::doPostForm(struct ofxHttpForm &)" (?doPostForm@ofxHttpUtils@@IAE?AUofxHttpResponse@@AAUofxHttpForm@@@Z) referenced in function
